//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiOnBoarding.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProyectoOnboardingEntities : DbContext
    {
        public dbProyectoOnboardingEntities()
            : base("name=dbProyectoOnboardingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OBTArea> OBTArea { get; set; }
        public virtual DbSet<OBTAspectosConductuales> OBTAspectosConductuales { get; set; }
        public virtual DbSet<OBTAspectoTecnico> OBTAspectoTecnico { get; set; }
        public virtual DbSet<OBTAspectoTecnicoActividad> OBTAspectoTecnicoActividad { get; set; }
        public virtual DbSet<OBTDetalleAspectos> OBTDetalleAspectos { get; set; }
        public virtual DbSet<OBTEmpleado> OBTEmpleado { get; set; }
        public virtual DbSet<OBTPuesto> OBTPuesto { get; set; }
        public virtual DbSet<OBTRecurso> OBTRecurso { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
